title = "Preferences example"

[settings."switch"]
category = "switch"
title = "Title"
summary = "summary"
defaultValue = true

[settings."input"]
category = "input"
title = "This is an input"
summary = ""
valueType = "STRING"  # STRING, NUMBER
defaultValue = "1234"
placeholder = "Please enter..."

[settings."textarea"]
category = "textarea"
title = "This is a textarea"
summary = "summary"
defaultValue = "Content"
placeholder = "Placeholder"

[settings."select"]
category = "select"
title = "Select"
summary = "summary"
options = ["A", "B", "C", "D"]
defaultValue = 0  # A index in options.
